@echo off
echo ========================================
echo EDRH Release Build Script v0.9.5
echo ========================================

:: Set variables
set "RELEASE_DIR=C:\Users\Admin\Downloads\EDRH_redo\EDRH_m\build\Desktop_Qt_6_9_1_MinGW_64_bit-Release"
set "BUILD_DIR=C:\Users\Admin\Downloads\EDRH_redo\EDRH_m\build"
set "PROJECT_DIR=C:\Users\Admin\Downloads\EDRH_redo\EDRH_m"
set "QT_BIN=C:\Qt\6.9.1\mingw_64\bin"
set "WINDEPLOYQT=%QT_BIN%\windeployqt.exe"
set "MAKENSIS=C:\Program Files (x86)\NSIS\makensis.exe"

:: Check if release build exists
if not exist "%RELEASE_DIR%\EDRH_m.exe" (
    echo ERROR: Release build not found at %RELEASE_DIR%\EDRH_m.exe
    echo Please build the project in Release mode first!
    pause
    exit /b 1
)

:: Clean up previous installer files
echo Cleaning up previous installer files...
if exist "%BUILD_DIR%\installer.nsi" del "%BUILD_DIR%\installer.nsi"
if exist "%BUILD_DIR%\EDRH_v0.9.5_Setup.exe" del "%BUILD_DIR%\EDRH_v0.9.5_Setup.exe"

echo Working directly with release directory: %RELEASE_DIR%

:: Check if windeployqt exists
if not exist "%WINDEPLOYQT%" (
    echo ERROR: windeployqt.exe not found at %WINDEPLOYQT%
    echo Please check your Qt installation path!
    pause
    exit /b 1
)

:: Run windeployqt directly on release directory
echo Running windeployqt on release directory...
echo Command: "%WINDEPLOYQT%" --qmldir "%PROJECT_DIR%\qml" --release --no-translations --no-system-d3d-compiler --no-opengl-sw "%RELEASE_DIR%\EDRH_m.exe"
"%WINDEPLOYQT%" --qmldir "%PROJECT_DIR%\qml" --release --no-translations --no-system-d3d-compiler --no-opengl-sw "%RELEASE_DIR%\EDRH_m.exe"

if %ERRORLEVEL% neq 0 (
    echo ERROR: windeployqt failed!
    pause
    exit /b 1
)

:: Copy additional required files to release directory
echo Copying additional files to release directory...

:: Copy assets if they exist
if exist "%PROJECT_DIR%\assets" (
    echo Copying assets...
    xcopy "%PROJECT_DIR%\assets" "%RELEASE_DIR%\assets\" /E /I /H /Y
)

:: Copy config file if it exists
if exist "%PROJECT_DIR%\config.json" (
    echo Copying config.json...
    copy "%PROJECT_DIR%\config.json" "%RELEASE_DIR%\"
)

:: Check for OpenSSL DLLs and copy them
set "OPENSSL_DIR=%QT_BIN%"
if exist "%OPENSSL_DIR%\libssl-3-x64.dll" (
    echo Copying OpenSSL libraries...
    copy "%OPENSSL_DIR%\libssl-3-x64.dll" "%RELEASE_DIR%\"
    copy "%OPENSSL_DIR%\libcrypto-3-x64.dll" "%RELEASE_DIR%\"
) else (
    echo WARNING: OpenSSL DLLs not found in Qt bin directory
    echo You may need to copy them manually for HTTPS functionality
)

:: Create NSIS installer script in build directory
echo Creating NSIS installer script in build directory...
(
echo ; EDRH Installer Script v0.9.5
echo ; Auto-generated by build_release.bat
echo.
echo !include "MUI2.nsh"
echo.
echo ; Application Information
echo Name "EDRH - Elite Dangerous Records Helper"
echo OutFile "EDRH_v0.9.5_Setup.exe"
echo InstallDir "$PROGRAMFILES\EDRH"
echo InstallDirRegKey HKLM "Software\EDRH" "InstallDir"
echo RequestExecutionLevel admin
echo.
echo ; Interface Settings
echo !define MUI_ABORTWARNING
echo !define MUI_FINISHPAGE_RUN "$INSTDIR\EDRH_m.exe"
echo !define MUI_FINISHPAGE_RUN_TEXT "Run EDRH now"
echo !define MUI_FINISHPAGE_SHOWREADME_NOTCHECKED
echo !define MUI_FINISHPAGE_SHOWREADME ""
echo !define MUI_FINISHPAGE_SHOWREADME_TEXT "Create desktop shortcut"
echo !define MUI_FINISHPAGE_SHOWREADME_FUNCTION CreateDesktopShortcut
echo.
echo ; Installer Pages
echo !insertmacro MUI_PAGE_WELCOME
echo !insertmacro MUI_PAGE_DIRECTORY
echo !insertmacro MUI_PAGE_INSTFILES
echo !insertmacro MUI_PAGE_FINISH
echo.
echo ; Uninstaller Pages
echo !insertmacro MUI_UNPAGE_CONFIRM
echo !insertmacro MUI_UNPAGE_INSTFILES
echo.
echo ; Languages
echo !insertmacro MUI_LANGUAGE "English"
echo.
echo ; Installation Section
echo Section "EDRH Application" SecMain
echo     SetOutPath "$INSTDIR"
echo     
echo     ; Copy all files from release directory
echo     File /r "%RELEASE_DIR%\*"
echo     
echo     ; Create uninstaller
echo     WriteUninstaller "$INSTDIR\Uninstall.exe"
echo     
echo     ; Registry entries
echo     WriteRegStr HKLM "Software\EDRH" "InstallDir" "$INSTDIR"
echo     WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "DisplayName" "EDRH - Elite Dangerous Records Helper"
echo     WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "UninstallString" "$INSTDIR\Uninstall.exe"
echo     WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "DisplayVersion" "0.9.5"
echo     WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "Publisher" "EDRH Team"
echo     WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "NoModify" 1
echo     WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH" "NoRepair" 1
echo     
echo     ; Start Menu shortcuts
echo     CreateDirectory "$SMPROGRAMS\EDRH"
echo     CreateShortcut "$SMPROGRAMS\EDRH\EDRH.lnk" "$INSTDIR\EDRH_m.exe"
echo     CreateShortcut "$SMPROGRAMS\EDRH\Uninstall EDRH.lnk" "$INSTDIR\Uninstall.exe"
echo SectionEnd
echo.
echo ; Uninstaller Section
echo Section "Uninstall"
echo     Delete "$INSTDIR\*.*"
echo     Delete "$INSTDIR\lib\*.*"
echo     Delete "$INSTDIR\assets\*.*"
echo     RMDir /r "$INSTDIR\lib"
echo     RMDir /r "$INSTDIR\assets"
echo     RMDir /r "$INSTDIR"
echo     
echo     DeleteRegKey HKLM "Software\EDRH"
echo     DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\EDRH"
echo     
echo     Delete "$SMPROGRAMS\EDRH\*.*"
echo     RMDir "$SMPROGRAMS\EDRH"
echo     Delete "$DESKTOP\EDRH.lnk"
echo SectionEnd
echo.
echo ; Desktop shortcut function
echo Function CreateDesktopShortcut
echo     CreateShortcut "$DESKTOP\EDRH.lnk" "$INSTDIR\EDRH_m.exe"
echo FunctionEnd
) > "%BUILD_DIR%\installer.nsi"

:: Check if NSIS is installed
if not exist "%MAKENSIS%" (
    echo WARNING: NSIS not found at %MAKENSIS%
    echo Please install NSIS or update the path in this script
    echo You can manually run the installer creation later
    goto :end
)

:: Create installer (run NSIS from build directory)
echo Creating NSIS installer...
echo Command: "%MAKENSIS%" "%BUILD_DIR%\installer.nsi"
pushd "%BUILD_DIR%"
"%MAKENSIS%" installer.nsi
popd

if %ERRORLEVEL% neq 0 (
    echo ERROR: NSIS installer creation failed!
    pause
    exit /b 1
) else (
    echo SUCCESS: Installer created as %BUILD_DIR%\EDRH_v0.9.5_Setup.exe
)

:end
echo.
echo ========================================
echo BUILD COMPLETE!
echo ========================================
echo Release Directory: %RELEASE_DIR%
echo NSIS Script: %BUILD_DIR%\installer.nsi
echo Installer: %BUILD_DIR%\EDRH_v0.9.5_Setup.exe
echo.
echo You can now distribute the installer or the release directory.
echo The release directory contains everything needed to run EDRH.
echo ========================================
pause
